
UIBuilder ui = new UIBuilder(base.Slot, null);
RectTransform listContainer;
RectTransform dataContainer;
ui.SplitHorizontally(0.25f, out listContainer, out dataContainer, 0f);
ui = new UIBuilder(listContainer);

RectTransform searchBar;
RectTransform list;
ui.HorizontalHeader(32f, out searchBar, out list);
ui = new UIBuilder(searchBar);

this._searchBar.Target = ui.TextField("", false, null, true, "Contacts.SearchPrompt".AsLocaleKey("<alpha=#44>{0}</alpha>", true, null));
this._searchBar.Target.Editor.Target.EditingChanged.Target = new Action<TextEditor>(this.SearchTextChanged);
ui = new UIBuilder(list);

UIBuilder uibuilder = ui;
Image image = uibuilder.Panel(in colorX, false);
image.Sprite.Target = ui.Style.ButtonSprite;
image.NineSliceSizing.Value = ui.Style.NineSliceSizing;
ui.ScrollArea(null);
ui.VerticalLayout(4f, 4f, null, null, null);
ui.FitContent(SizeFit.Disabled, SizeFit.PreferredSize);
this._listRoot.Target = ui.Root;
this.listUi = ui;
this.listUi.Style.MinHeight = 32f;
this.listUi.Style.TextAutoSizeMin = 0f;
ui = new UIBuilder(dataContainer);
RectTransform header;
RectTransform feedsContainer;
ui.HorizontalHeader(96f, out header, out feedsContainer);
ui = new UIBuilder(header);
RectTransform avatar;
RectTransform userUi;
ui.VerticalHeader(96f, out avatar, out userUi);
ui = new UIBuilder(avatar);
this._status.Target = ui.Image(ui.CircleSprite, true);
ui.Nest();
ui.SpriteMask(ui.CircleSprite, false);//this is the icon code
ui.Nest();
this._avatar.Target = ui.Image();
ui = new UIBuilder(userUi);
RectTransform userTop;
RectTransform userBottom;
ui.SplitVertically(0.5f, out userTop, out userBottom, 0f);
ui = new UIBuilder(userTop);
SyncRef<Text> username = this._username;
UIBuilder uibuilder2 = ui;
LocaleString localeString = "---";
username.Target = uibuilder2.Text(in localeString, true, null, true, null);
ui = new UIBuilder(userBottom);
ui.HorizontalLayout(4f, 4f, null);
ui.FitContent(SizeFit.PreferredSize, SizeFit.Disabled);
ui.Style.PreferredWidth = 96f;
this._userActionsRoot.Target = ui.Root;
this.actionsUi = ui;
ui = new UIBuilder(feedsContainer);
RectTransform sessions;
RectTransform messages;
ui.SplitHorizontally(0.5f, out sessions, out messages, 0f);// Message creation
ui = new UIBuilder(sessions);
UIBuilder uibuilder3 = ui;
Image image2 = uibuilder3.Panel(in colorX, false);
image2.Sprite.Target = ui.Style.ButtonSprite;
image2.NineSliceSizing.Value = ui.Style.NineSliceSizing;
ui.ScrollArea(null);
ui.VerticalLayout(4f, 4f, null, null, null);
ui.FitContent(SizeFit.Disabled, SizeFit.PreferredSize);
this.sessionsUi = ui;
this.sessionsUi.Style.MinHeight = 64f;
this.sessionsUi.Style.TextAutoSizeMin = 0f;
this._sessionsRoot.Target = ui.Root;
ui = new UIBuilder(messages);
RectTransform messageTextBox;
RectTransform messagesContainer;
ui.HorizontalFooter(36f, out messageTextBox, out messagesContainer);
ui = new UIBuilder(messageTextBox);
RectTransform sendButtonRoot;
RectTransform messageTextRoot;
ui.VerticalFooter(84f, out sendButtonRoot, out messageTextRoot);
ui = new UIBuilder(sendButtonRoot);
ui.HorizontalLayout(4f, 0f, null);
SyncRef<Button> sendMessageButton = this._sendMessageButton;
UIBuilder uibuilder4 = ui;
Uri send = OfficialAssets.Graphics.Icons.General.Send;
colorX = colorX.White;
sendMessageButton.Target = uibuilder4.Button(send, in colorX2, in colorX, new ButtonEventHandler(this.OnSendMessage), 0f);
SyncRef<Button> sendVoiceMessageButton = this._sendVoiceMessageButton;
UIBuilder uibuilder5 = ui;
localeString = "●";
sendVoiceMessageButton.Target = uibuilder5.Button(in localeString, in colorX2);
this._sendVoiceMessageButton.Target.EnabledField.DriveFrom(this._sendMessageButton.Target.EnabledField, false, false, true);
this._sendVoiceMessageButton.Target.Pressed.Target = new ButtonEventHandler(this.OnStartRecordingVoiceMessage);
this._sendVoiceMessageButton.Target.Released.Target = new ButtonEventHandler(this.OnStopRecordingVoiceMessage);
this._sendVoiceMessageButton.Target.PassThroughHorizontalMovement.Value = false;
this._sendVoiceMessageButton.Target.PassThroughVerticalMovement.Value = false;
ui = new UIBuilder(messageTextRoot);
this._sendMessageTextField.Target = ui.TextField("", false, null, true, "Contacts.WriteMessage".AsLocaleKey("<alpha=#44>{0}</alpha>", true, null));
this._sendMessageTextField.Target.Editor.Target.SubmitPressed.Target = new Action<TextEditor>(this.MessageSubmitPressed);
this._sendMessageTextField.Target.Slot.GetComponent<Button>(null, false).EnabledField.DriveFrom(this._sendMessageButton.Target.EnabledField, false, false, true);
ui = new UIBuilder(messagesContainer);
UIBuilder uibuilder6 = ui;
Image image3 = uibuilder6.Panel(in colorX, false);
image3.Sprite.Target = ui.Style.ButtonSprite;
image3.NineSliceSizing.Value = ui.Style.NineSliceSizing;
this._messagesScrollRect.Target = ui.ScrollArea(null);
ui.VerticalLayout(4f, 4f, null, null, null);
ui.FitContent(SizeFit.Disabled, SizeFit.PreferredSize);
ui.Style.MinHeight = 24f;
this._messagesRoot.Target = ui.Root;
this.messagesUi = ui;
base.Engine.Cloud.Contacts.ContactAdded += this.Contacts_ContactAdded;
base.Engine.Cloud.Contacts.ContactUpdated += this.Contacts_ContactUpdated;
base.Engine.Cloud.Contacts.ContactRemoved += this.Contacts_ContactRemoved;
base.Engine.Cloud.Contacts.ContactStatusChanged += this.Contacts_ContactStatusChanged;
base.Engine.Cloud.Messages.OnMessageSent += this.Messages_OnMessageSent;
base.Engine.Cloud.Messages.OnMessageReceived += this.Messages_OnMessageReceived;
base.Engine.Cloud.Messages.OnMessageRead += this.Messages_OnMessageRead;
base.Engine.Cloud.Messages.UnreadMessageCountChanged += this.Messages_UnreadMessageCountChanged;
base.Engine.Cloud.Contacts.ForeachContactData(delegate(ContactData data)
{
	this.UpdateContactItem(data);
});
this.UpdateSelectedContact();